version: '2'

services:
  can.klantbeheer.facade:
    image: candilever/can.klantbeheer.facade
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      dbconnectionstring: Server=can_klantbeheer_mssql;Database=CAN_Klantbeheer;User Id=sa;Password=P@55w0rd;
      eventbus-exchangename: KantileverBus
      eventbus-queuename: bestellingbeheer
      eventbus-hostname: can-kantilever-eventbus
      eventbus-username: Kantilever
      eventbus-password: Kant1lever
      logpath: /var/log/Kantilever/KlantbeheerLogging/
    ports:
      - 11400:80
    networks:
      can_klantbeheer_network:
      can_main_network:
        aliases:
          - can-klantbeheer
    volumes:
      - "C:/Docker/.KlantbeheerData/Log:/var/log/Kantilever/KlantbeheerLogging/"
    depends_on:
      - can.klantbeheer.mssql

  can.klantbeheer.mssql:
    image: microsoft/mssql-server-linux
    container_name: can_klantbeheer_mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@55w0rd
    networks:
      - can_klantbeheer_network
    ports:
      - 11410:1433
    volumes:
      - "C:/Docker/.KlantbeheerData/db:/var/opt/mssql/"


networks:
  can_main_network: 
    external:
      name: can_main_network
  can_klantbeheer_network: