// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CAN.BackOffice.Agents.AuthenticatieAgents.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ErrorResult
    {
        /// <summary>
        /// Initializes a new instance of the ErrorResult class.
        /// </summary>
        public ErrorResult() { }

        /// <summary>
        /// Initializes a new instance of the ErrorResult class.
        /// </summary>
        public ErrorResult(string errorMessage = default(string))
        {
            ErrorMessage = errorMessage;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessage")]
        public string ErrorMessage { get; set; }

    }
}
