// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CAN.BackOffice.Agents.AuthenticatieAgents.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class LoginResult
    {
        /// <summary>
        /// Initializes a new instance of the LoginResult class.
        /// </summary>
        public LoginResult() { }

        /// <summary>
        /// Initializes a new instance of the LoginResult class.
        /// </summary>
        public LoginResult(string accessToken = default(string), int? expiresIn = default(int?))
        {
            AccessToken = accessToken;
            ExpiresIn = expiresIn;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "access_Token")]
        public string AccessToken { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expires_In")]
        public int? ExpiresIn { get; private set; }

    }
}
