version: '2'

services:
  can.candeliver.backofficeauthenticatie:
    image: user/can.candeliver.backofficeauthenticatie${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
