// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CAN.Webwinkel.Agents.WinkelwagenAgent.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Bestelling
    {
        /// <summary>
        /// Initializes a new instance of the Bestelling class.
        /// </summary>
        public Bestelling() { }

        /// <summary>
        /// Initializes a new instance of the Bestelling class.
        /// </summary>
        public Bestelling(long klantnummer, string volledigeNaam, string postcode, string adres, string huisnummer, string land, string winkelmandjeNummer, DateTime? bestelDatum = default(DateTime?), int? status = default(int?))
        {
            Klantnummer = klantnummer;
            VolledigeNaam = volledigeNaam;
            Postcode = postcode;
            Adres = adres;
            Huisnummer = huisnummer;
            Land = land;
            WinkelmandjeNummer = winkelmandjeNummer;
            BestelDatum = bestelDatum;
            Status = status;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "klantnummer")]
        public long Klantnummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "volledigeNaam")]
        public string VolledigeNaam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postcode")]
        public string Postcode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adres")]
        public string Adres { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "huisnummer")]
        public string Huisnummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "land")]
        public string Land { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "winkelmandjeNummer")]
        public string WinkelmandjeNummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bestelDatum")]
        public DateTime? BestelDatum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public int? Status { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (VolledigeNaam == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "VolledigeNaam");
            }
            if (Postcode == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Postcode");
            }
            if (Adres == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Adres");
            }
            if (Huisnummer == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Huisnummer");
            }
            if (Land == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Land");
            }
            if (WinkelmandjeNummer == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "WinkelmandjeNummer");
            }
        }
    }
}
