// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CAN.Webwinkel.Agents.WinkelwagenAgent.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Winkelmandje
    {
        /// <summary>
        /// Initializes a new instance of the Winkelmandje class.
        /// </summary>
        public Winkelmandje() { }

        /// <summary>
        /// Initializes a new instance of the Winkelmandje class.
        /// </summary>
        public Winkelmandje(long? id = default(long?), string winkelmandjeNummer = default(string), IList<ArtikelDTO> artikelen = default(IList<ArtikelDTO>))
        {
            Id = id;
            WinkelmandjeNummer = winkelmandjeNummer;
            Artikelen = artikelen;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "winkelmandjeNummer")]
        public string WinkelmandjeNummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "artikelen")]
        public IList<ArtikelDTO> Artikelen { get; set; }

    }
}
