// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CAN.BackOffice.Agents.BestellingsAgent.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Bestelling
    {
        /// <summary>
        /// Initializes a new instance of the Bestelling class.
        /// </summary>
        public Bestelling() { }

        /// <summary>
        /// Initializes a new instance of the Bestelling class.
        /// </summary>
        public Bestelling(long klantnummer, long? bestellingnummer = default(long?), IList<Artikel> artikelen = default(IList<Artikel>), DateTime? bestelDatum = default(DateTime?))
        {
            Bestellingnummer = bestellingnummer;
            Klantnummer = klantnummer;
            Artikelen = artikelen;
            BestelDatum = bestelDatum;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bestellingnummer")]
        public long? Bestellingnummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "klantnummer")]
        public long Klantnummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "artikelen")]
        public IList<Artikel> Artikelen { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bestelDatum")]
        public DateTime? BestelDatum { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Artikelen != null)
            {
                foreach (var element in this.Artikelen)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
