// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CAN.BackOffice.Agents.BestellingsAgent.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BestellingDTO
    {
        /// <summary>
        /// Initializes a new instance of the BestellingDTO class.
        /// </summary>
        public BestellingDTO() { }

        /// <summary>
        /// Initializes a new instance of the BestellingDTO class.
        /// </summary>
        public BestellingDTO(long klantnummer, string volledigeNaam, string postcode, string adres, string huisnummer, string land, long? bestellingnummer = default(long?), IList<ArtikelDTO> artikelen = default(IList<ArtikelDTO>), DateTime? bestelDatum = default(DateTime?), int? status = default(int?))
        {
            Bestellingnummer = bestellingnummer;
            Klantnummer = klantnummer;
            VolledigeNaam = volledigeNaam;
            Postcode = postcode;
            Adres = adres;
            Huisnummer = huisnummer;
            Land = land;
            Artikelen = artikelen;
            BestelDatum = bestelDatum;
            Status = status;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bestellingnummer")]
        public long? Bestellingnummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "klantnummer")]
        public long Klantnummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "volledigeNaam")]
        public string VolledigeNaam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postcode")]
        public string Postcode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adres")]
        public string Adres { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "huisnummer")]
        public string Huisnummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "land")]
        public string Land { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "artikelen")]
        public IList<ArtikelDTO> Artikelen { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bestelDatum")]
        public DateTime? BestelDatum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public int? Status { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (VolledigeNaam == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "VolledigeNaam");
            }
            if (Postcode == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Postcode");
            }
            if (Adres == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Adres");
            }
            if (Huisnummer == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Huisnummer");
            }
            if (Land == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Land");
            }
            if (this.Artikelen != null)
            {
                foreach (var element in this.Artikelen)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
