// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace CAN.BackOffice.Agents.AuthenticatieAgents.Agents
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for AuthenticatieService.
    /// </summary>
    public static partial class AuthenticatieServiceExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object BackOfficeLogin(this IAuthenticatieService operations, LoginViewModel model = default(LoginViewModel))
            {
                return Task.Factory.StartNew(s => ((IAuthenticatieService)s).BackOfficeLoginAsync(model), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> BackOfficeLoginAsync(this IAuthenticatieService operations, LoginViewModel model = default(LoginViewModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.BackOfficeLoginWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object BackOfficeRegister(this IAuthenticatieService operations, RegisterViewModel model = default(RegisterViewModel))
            {
                return Task.Factory.StartNew(s => ((IAuthenticatieService)s).BackOfficeRegisterAsync(model), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> BackOfficeRegisterAsync(this IAuthenticatieService operations, RegisterViewModel model = default(RegisterViewModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.BackOfficeRegisterWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
